import { Game } from "./types";

export const GAMES: Game[] = [
  {
    id: "cyber-strike",
    title: "Cyber Strike (شوتر القلابي)",
    description: "لعبة تصويب من منظور الشخص الأول (FPS) بسيطة داخل المتصفح، تعتمد على السرعة، واللاعبين يتنافسون مين يجيب Headshots أكثر.",
    category: "Action / Shooter",
    image: "https://picsum.photos/seed/shooter/800/450",
    minPlayers: 2,
    maxPlayers: 5,
  },
  {
    id: "neon-racer",
    title: "Neon Racer (سباق الهجولة)",
    description: "لعبة سباق سيارات من منظور علوي، فيها درافت وتحدي مين يوصل لخط النهاية أول بدون ما يصدم.",
    category: "Racing",
    image: "https://picsum.photos/seed/racing/800/450",
    minPlayers: 2,
    maxPlayers: 5,
  },
  {
    id: "escape-house",
    title: "Escape from the House (الهروب من البيت)",
    description: "واحد يكون الجزار والباقين يهربون في بيت مظلم. لازم يجمعون مفاتيح عشان يفتحون الباب.",
    category: "Horror",
    image: "https://picsum.photos/seed/horror/800/450",
    minPlayers: 2,
    maxPlayers: 5,
  },
  {
    id: "horror-maze",
    title: "Horror Maze (المستشفى المهجور)",
    description: "لعبة رعب تعتمد على الأصوات المرعبة والممرات الضيقة، والهدف هو البحث عن غرض معين والهروب.",
    category: "Horror",
    image: "https://picsum.photos/seed/maze/800/450",
    minPlayers: 1,
    maxPlayers: 5,
  },
  {
    id: "the-outlier",
    title: "The Outlier (برا السالفة)",
    description: "كل أخوياك يعرفون الكلمة إلا واحد. لازم يحاول يرقع وما يبين أنه ما يدري وش الموضوع.",
    category: "Social / Party",
    image: "https://picsum.photos/seed/party/800/450",
    minPlayers: 3,
    maxPlayers: 5,
  },
  {
    id: "answer-theirs",
    title: "Your Answer vs Theirs (جوابك وجوابهم)",
    description: "تطلع أسئلة شاطحة، والكل يجاوب، وفي النهاية تصوتون على أضحك جواب.",
    category: "Social / Party",
    image: "https://picsum.photos/seed/qa/800/450",
    minPlayers: 3,
    maxPlayers: 5,
  },
  {
    id: "al-rassam",
    title: "Al-Rassam (رسم وتخمين)",
    description: "السبورة التفاعلية؛ واحد يرسم والباقين يكتبون في الشات، والنقاط تروح للأسرع.",
    category: "Social / Party",
    image: "https://picsum.photos/seed/draw/800/450",
    minPlayers: 2,
    maxPlayers: 5,
  },
  {
    id: "high-low",
    title: "High/Low (فوق ولا تحت 50؟)",
    description: "لعبة أرقام سريعة للمراهنة بنقاط الموقع، يتوقع الرقم اللي بعده فوق الـ 50 أو تحته.",
    category: "Betting / Quick",
    image: "https://picsum.photos/seed/numbers/800/450",
    minPlayers: 1,
    maxPlayers: 5,
  },
  {
    id: "uno",
    title: "Uno (أونو)",
    description: "لعبة البطاقات الشهيرة، تحدى أصدقائك وكن أول من يتخلص من بطاقاته.",
    category: "Board Game",
    image: "https://picsum.photos/seed/cards/800/450",
    minPlayers: 2,
    maxPlayers: 5,
  },
  {
    id: "ludo",
    title: "Ludo (لودو)",
    description: "لعبة لودو الكلاسيكية، حرك قطعك للوصول إلى المركز قبل الآخرين.",
    category: "Board Game",
    image: "https://picsum.photos/seed/ludo/800/450",
    minPlayers: 2,
    maxPlayers: 4,
  },
  {
    id: "carrom",
    title: "Carrom (كيرم)",
    description: "لعبة الكيرم التقليدية، دقة وتركيز لإسقاط الأقراص في الجيوب.",
    category: "Board Game",
    image: "https://picsum.photos/seed/carrom/800/450",
    minPlayers: 2,
    maxPlayers: 4,
  }
];
